[build]
  base    = "web"
  command = "npm ci && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev --prefix web"  # run Vite
  targetPort = 5173                     # Vite dev server port
  functions = "netlify/functions"
  publish = "web"
  port = 8888                           # Netlify Dev proxy port
